version: '3'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./api:/var/www/api
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - internal

    # php
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: api
        ports:
            - "9000:9000"
        volumes:
            - ./api:/var/www/api
        networks:
            - internal

    # mysql
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - 4306:3306
        volumes:
            - db-data:/var/lib/mysql
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: chopein
            MYSQL_PASSWORD: chopein
            MYSQL_DATABASE: chopein
        networks:
            - internal

    front:
        container_name: front
        restart: always # always restart unless stopped manually
        build:
            context: .
            dockerfile: ./front/Dockerfile
        volumes:
        - "./front:/front"
        ports:
        - 3001:3000
        environment:
        - CHOKIDAR_USEPOLLING=true
        networks:
            - internal
        stdin_open: true

networks:
    internal:
volumes:
    db-data: {}