version: '3'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./api:/var/www/api
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - internal

    # php
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./api:/var/www/api
        networks:
            - internal

    # mysql
    mysql:
        image: mysql:8
        container_name: mysql-container
        ports:
            - "4306:3306"
        volumes:
            - ./db-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: chopein
            MYSQL_ROOT_PASSWORD: chopein
            MYSQL_PASSWORD: chopein
        networks:
            - internal

    # node
    node-service:
        image: node:16
        container_name: node-container
        volumes:
            - ./front:/var/www/front
        working_dir: /var/www/front
        networks:
            - internal

networks:
    internal:

volumes:
    db-data: